package org.appwork.fileiconexport;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;

/**
 * This file was autogenerated by <a
 * href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that
 * <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a
 * few opensource projects.</a>.<br>
 * For help, please visit <a
 * href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a
 * href="http://rococoa.dev.java.net/">Rococoa</a>, or <a
 * href="http://jna.dev.java.net/">JNA</a>.
 */
public class GRPICONDIRENTRY extends Structure {

    // / Width, in pixels, of the image
    public byte  bWidth;
    // / Height, in pixels, of the image
    public byte  bHeight;
    // / Number of colors in image (0 if >=8bpp)
    public byte  bColorCount;
    // / Reserved
    public byte  bReserved;
    // / Color Planes
    public short wPlanes;
    // / Bits per pixel
    public short wBitCount;
    // / how many bytes in this resource?
    public int   dwBytesInRes;
    // / the ID
    public short nID;

    public GRPICONDIRENTRY(final Pointer entriesPointer) {
        super(entriesPointer);
        this.initFieldOrder();
        this.read();

    }

    protected void initFieldOrder() {
        this.setFieldOrder(new java.lang.String[] { "bWidth", "bHeight", "bColorCount", "bReserved", "wPlanes", "wBitCount", "dwBytesInRes", "nID" });
    };
}
