package org.jdownloader.plugins.controller.host;

import java.util.List;
import java.util.ArrayList;
import java.util.Arrays;

import jd.plugins.PluginForHost;

import org.jdownloader.plugins.controller.PluginInfo;

public class StaticHostPlugins {
    private static final List<Class<?>> CLASSES = Arrays.<Class<?>>asList(
       jd.plugins.hoster.ARDMediathek.class,
jd.plugins.hoster.ASheMaleTubeCom.class,
jd.plugins.hoster.AbbyWintersCom.class,
jd.plugins.hoster.AbelhasPt.class,
jd.plugins.hoster.AboutCom.class,
jd.plugins.hoster.AcapellasFourYouCoUk.class,
jd.plugins.hoster.AdriveCom.class,
jd.plugins.hoster.AiminiNet.class,
// jd.plugins.hoster.AkaFileCom.class,
jd.plugins.hoster.AkatsukiSubsNet.class,
jd.plugins.hoster.AlbaFileCom.class,
jd.plugins.hoster.AllDebridCom.class,
jd.plugins.hoster.AllMyVideosNet.class,
jd.plugins.hoster.AlotPornCom.class,
jd.plugins.hoster.AlphaPornoCom.class,
jd.plugins.hoster.AlterVideoNet.class,
jd.plugins.hoster.AmazonCloud.class,
jd.plugins.hoster.AmonShareCom.class,
jd.plugins.hoster.AnaFileCom.class,
jd.plugins.hoster.AndroidFileHostCom.class,
jd.plugins.hoster.AnimePremiumTv.class,
jd.plugins.hoster.AnimeTheHyliaCom.class,
jd.plugins.hoster.AnimeUltimeNet.class,
jd.plugins.hoster.AnimeUploadsCom.class,
jd.plugins.hoster.AnimeaNet.class,
jd.plugins.hoster.AnitubeCo.class,
jd.plugins.hoster.AnonFilesCom.class,
jd.plugins.hoster.AnonymousDeliversUs.class,
jd.plugins.hoster.Antena3Com.class,
jd.plugins.hoster.AnySendCom.class,
jd.plugins.hoster.AnySexCom.class,
jd.plugins.hoster.ArabLoadsCom.class,
jd.plugins.hoster.ArteTv.class,
// jd.plugins.hoster.AsFileCom.class,
jd.plugins.hoster.AuEngineCom.class,
jd.plugins.hoster.AudioMa.class,
jd.plugins.hoster.AudioRokCom.class,
jd.plugins.hoster.AxiFileCom.class,
// jd.plugins.hoster.BackinNet.class,
jd.plugins.hoster.BadJoJoCom.class,
jd.plugins.hoster.BaixarPremiumNet.class,
jd.plugins.hoster.BandCampCom.class,
jd.plugins.hoster.BangYouLaterCom.class,
jd.plugins.hoster.BaniCrazyInfo.class,
jd.plugins.hoster.BasicUploadCom.class,
jd.plugins.hoster.BatShareCom.class,
jd.plugins.hoster.BayFilesCom.class,
// jd.plugins.hoster.BeStreamsNet.class,
jd.plugins.hoster.BeegCom.class,
jd.plugins.hoster.BeroFileCom.class,
jd.plugins.hoster.BestPornTubeMe.class,
jd.plugins.hoster.BezVadataCz.class,
jd.plugins.hoster.BigBootyCom.class,
jd.plugins.hoster.BigDownloaderCom.class,
// jd.plugins.hoster.BillionUploadsCom.class,
jd.plugins.hoster.BinGe.class,
jd.plugins.hoster.BitCasaCom.class,
jd.plugins.hoster.BitShareCom.class,
jd.plugins.hoster.BlipTv.class,
jd.plugins.hoster.BlitzFilesCom.class,
jd.plugins.hoster.BlueFishTvCom.class,
jd.plugins.hoster.BlueHasteCom.class,
jd.plugins.hoster.BollywoodHungamaCom.class,
jd.plugins.hoster.BooJourEu.class,
jd.plugins.hoster.BookFiOrg.class,
jd.plugins.hoster.BoosterKingCom.class,
jd.plugins.hoster.BornCashOrg.class,
jd.plugins.hoster.BoxCaCom.class,
jd.plugins.hoster.BoxNet.class,
jd.plugins.hoster.BrOnlineDe.class,
jd.plugins.hoster.BravoTubeNet.class,
jd.plugins.hoster.BreakCom.class,
jd.plugins.hoster.BubbleFilesCom.class,
jd.plugins.hoster.BurningCamelCom.class,
jd.plugins.hoster.ByZooOrg.class,
jd.plugins.hoster.ByteBxCom.class,
jd.plugins.hoster.BytesBoxCom.class,
jd.plugins.hoster.CZShareCom.class,
jd.plugins.hoster.CamelStyleNet.class,
jd.plugins.hoster.CarrierSo.class,
jd.plugins.hoster.CatShareNet.class,
jd.plugins.hoster.CatShareOrg.class,
jd.plugins.hoster.CestyKsobeCz.class,
jd.plugins.hoster.ChThnhInfo.class,
jd.plugins.hoster.ChipDe.class,
jd.plugins.hoster.ChoMikujPl.class,
jd.plugins.hoster.ClickToViewOrg.class,
jd.plugins.hoster.ClipHunterCom.class,
jd.plugins.hoster.ClipfishDe.class,
jd.plugins.hoster.ClipsAndPicsOrg.class,
jd.plugins.hoster.CloudMailRu.class,
jd.plugins.hoster.CloudStorEs.class,
jd.plugins.hoster.CloudVidzCom.class,
jd.plugins.hoster.CloudZillaTo.class,
jd.plugins.hoster.CloudyVideosCom.class,
jd.plugins.hoster.CnetCom.class,
jd.plugins.hoster.CobraBe.class,
jd.plugins.hoster.CokluindirCom.class,
jd.plugins.hoster.ColaFileCom.class,
jd.plugins.hoster.Come2StoreCom.class,
jd.plugins.hoster.CometFilesCom.class,
jd.plugins.hoster.ConexaomegaCom.class,
jd.plugins.hoster.CoolMovsCom.class,
jd.plugins.hoster.CopyCom.class,
jd.plugins.hoster.CosmoBoxOrg.class,
jd.plugins.hoster.CraMitIn.class,
jd.plugins.hoster.CrackedCom.class,
jd.plugins.hoster.CreaFileCom.class,
jd.plugins.hoster.CreaFileNet.class,
jd.plugins.hoster.CrisShareCom.class,
jd.plugins.hoster.CrockoCom.class,
jd.plugins.hoster.CrunchyRollCom.class,
jd.plugins.hoster.CtDiskCom.class,
jd.plugins.hoster.CxCom.class,
jd.plugins.hoster.DBankCom.class,
jd.plugins.hoster.DaClipsIn.class,
jd.plugins.hoster.DailyMotionCom.class,
jd.plugins.hoster.DajTo.class,
jd.plugins.hoster.DatPiffCom.class,
// jd.plugins.hoster.DataFileCom.class,
jd.plugins.hoster.DataFileHostCom.class,
jd.plugins.hoster.DataHu.class,
jd.plugins.hoster.DatacodRu.class,
jd.plugins.hoster.DatagradRU.class,
jd.plugins.hoster.DateiTo.class,
jd.plugins.hoster.DatoidCz.class,
jd.plugins.hoster.DavvasCom.class,
jd.plugins.hoster.DdlStorageCom.class,
jd.plugins.hoster.DebridItaliaCom.class,
jd.plugins.hoster.DebridLinkFr.class,
jd.plugins.hoster.DeerFileCom.class,
// jd.plugins.hoster.DepositFiles.class,
jd.plugins.hoster.DeredactieBe.class,
jd.plugins.hoster.DeviantArtCom.class,
jd.plugins.hoster.DeviantClipCom.class,
jd.plugins.hoster.DhSt.class,
jd.plugins.hoster.DirectHTTP.class,
jd.plugins.hoster.Disk84DmCom.class,
jd.plugins.hoster.DiskFilesNet.class,
// jd.plugins.hoster.DiskYandexNet.class,
jd.plugins.hoster.DivShareCom.class,
jd.plugins.hoster.DivxDenCom.class,
jd.plugins.hoster.DivxHostedCom.class,
jd.plugins.hoster.DivxHostingNet.class,
jd.plugins.hoster.DivxPlanetCom.class,
jd.plugins.hoster.DivxPressCom.class,
jd.plugins.hoster.DivxStageNet.class,
jd.plugins.hoster.DiziPortCom.class,
// jd.plugins.hoster.DizzCloudCom.class,
jd.plugins.hoster.DjvvCom.class,
jd.plugins.hoster.DlFreeFr.class,
jd.plugins.hoster.DnbShareCom.class,
jd.plugins.hoster.DocsGoogleCom.class,
jd.plugins.hoster.DodanePl.class,
// jd.plugins.hoster.DogUploadCom.class,
jd.plugins.hoster.DoneVideoCom.class,
jd.plugins.hoster.DopeRomsCom.class,
jd.plugins.hoster.DoriDroNet.class,
jd.plugins.hoster.DosyaTc.class,
jd.plugins.hoster.DownFlowNet.class,
jd.plugins.hoster.DownItFasterCom.class,
jd.plugins.hoster.DownMastersCom.class,
jd.plugins.hoster.DownloadAndroidRomCom.class,
// jd.plugins.hoster.DownloadAniMe.class,
jd.plugins.hoster.DownloadHr.class,
jd.plugins.hoster.DownloadMe.class,
jd.plugins.hoster.DrTuberCom.class,
jd.plugins.hoster.DreiSatDe.class,
jd.plugins.hoster.DropCanVasCom.class,
jd.plugins.hoster.DropFilesInfo.class,
jd.plugins.hoster.DropVideoCom.class,
jd.plugins.hoster.DropboxCom.class,
jd.plugins.hoster.DroplrCom.class,
// jd.plugins.hoster.DumpFilesOrg.class,
jd.plugins.hoster.DuploadOrg.class,
jd.plugins.hoster.DwnSharePl.class,
jd.plugins.hoster.DwnSo.class,
jd.plugins.hoster.EHowCom.class,
jd.plugins.hoster.EPornerCom.class,
// jd.plugins.hoster.EasyBytezCom.class,
jd.plugins.hoster.EasyFileSharingCom.class,
jd.plugins.hoster.EasyFilesPl.class,
jd.plugins.hoster.EasydowCom.class,
jd.plugins.hoster.EbaGovTr.class,
jd.plugins.hoster.EbaumsWorldCom.class,
jd.plugins.hoster.EcoStreamTv.class,
jd.plugins.hoster.EdiskCz.class,
jd.plugins.hoster.EgoFilesCom.class,
jd.plugins.hoster.EightTracksCom.class,
jd.plugins.hoster.EltrecetvComAr.class,
jd.plugins.hoster.EmoHottiesCom.class,
jd.plugins.hoster.EmpFlixCom.class,
// jd.plugins.hoster.EpicShareNet.class,
jd.plugins.hoster.EroProfileCom.class,
jd.plugins.hoster.EroxiaCom.class,
jd.plugins.hoster.EsouboryCz.class,
jd.plugins.hoster.EuroShareEu.class,
jd.plugins.hoster.EvilAngelCom.class,
jd.plugins.hoster.ExFileRu.class,
// jd.plugins.hoster.ExLoadCom.class,
jd.plugins.hoster.ExStorageNet.class,
jd.plugins.hoster.ExaShareCom.class,
// jd.plugins.hoster.ExclusiveFaileCom.class,
// jd.plugins.hoster.ExpressLeechCom.class,
jd.plugins.hoster.ExtMatrixCom.class,
jd.plugins.hoster.ExtraDjCom.class,
jd.plugins.hoster.ExtreamRapidCom.class,
jd.plugins.hoster.ExtremeTubeCom.class,
jd.plugins.hoster.EyesFileCom.class,
jd.plugins.hoster.FBitRu.class,
// jd.plugins.hoster.FShareVn.class,
jd.plugins.hoster.FUploadNet.class,
// jd.plugins.hoster.FaceBookComVideos.class,
jd.plugins.hoster.FaiLaiLt.class,
jd.plugins.hoster.FanBridgeCom.class,
jd.plugins.hoster.FastFileShareComAr.class,
jd.plugins.hoster.FastShareCz.class,
jd.plugins.hoster.FastShareorg.class,
jd.plugins.hoster.FastStreamIn.class,
jd.plugins.hoster.FernsehkritikTv.class,
jd.plugins.hoster.FfDownloaderCom.class,
jd.plugins.hoster.FiberUploadCom.class,
jd.plugins.hoster.FilEarnCom.class,
jd.plugins.hoster.FilEarningCom.class,
jd.plugins.hoster.File1Info.class,
jd.plugins.hoster.File2HostCom.class,
jd.plugins.hoster.File4GoCom.class,
jd.plugins.hoster.File4SafeCom.class,
jd.plugins.hoster.FileBandCom.class,
jd.plugins.hoster.FileBeamCom.class,
jd.plugins.hoster.FileBigNet.class,
jd.plugins.hoster.FileBitPl.class,
jd.plugins.hoster.FileBiteCc.class,
jd.plugins.hoster.FileBlazeNet.class,
// jd.plugins.hoster.FileBoomMe.class,
jd.plugins.hoster.FileBrellaCom.class,
// jd.plugins.hoster.FileBulkCom.class,
jd.plugins.hoster.FileCanyonCom.class,
jd.plugins.hoster.FileChinCom.class,
jd.plugins.hoster.FileChumCom.class,
jd.plugins.hoster.FileCopterNet.class,
jd.plugins.hoster.FileDaisCom.class,
jd.plugins.hoster.FileDwonCom.class,
jd.plugins.hoster.FileFactory.class,
jd.plugins.hoster.FileFeltoltoHu.class,
jd.plugins.hoster.FileFilesNet.class,
jd.plugins.hoster.FileFlushCom.class,
jd.plugins.hoster.FileFlyerCom.class,
jd.plugins.hoster.FileGoOrg.class,
jd.plugins.hoster.FileHippoCom.class,
jd.plugins.hoster.FileHorseCom.class,
jd.plugins.hoster.FileHosterRu.class,
jd.plugins.hoster.FileImCom.class,
jd.plugins.hoster.FileJokerNet.class,
jd.plugins.hoster.FileJungleCom.class,
jd.plugins.hoster.FileKareliaRu.class,
jd.plugins.hoster.FileLaserCom.class,
jd.plugins.hoster.FileMadeCom.class,
jd.plugins.hoster.FileMakCom.class,
jd.plugins.hoster.FileMazeWs.class,
jd.plugins.hoster.FileMeUpNet.class,
jd.plugins.hoster.FileMoneyCom.class,
// jd.plugins.hoster.FileMonkeyIn.class,
jd.plugins.hoster.FileMovNet.class,
jd.plugins.hoster.FileMupCom.class,
jd.plugins.hoster.FileNukeCom.class,
jd.plugins.hoster.FileObozUa.class,
// jd.plugins.hoster.FileOmCom.class,
jd.plugins.hoster.FileOveCom.class,
jd.plugins.hoster.FileOverNet.class,
jd.plugins.hoster.FilePiCom.class,
// jd.plugins.hoster.FilePlanetaCom.class,
// jd.plugins.hoster.FilePostCom.class,
jd.plugins.hoster.FileProjectComBr.class,
jd.plugins.hoster.FilePupNet.class,
// jd.plugins.hoster.FilePurposeCom.class,
jd.plugins.hoster.FileQipRu.class,
jd.plugins.hoster.FileRioCom.class,
jd.plugins.hoster.FileSaurCom.class,
jd.plugins.hoster.FileSendNet.class,
jd.plugins.hoster.FileServeCom.class,
jd.plugins.hoster.FileShareTo.class,
jd.plugins.hoster.FileSpaceOrg.class,
jd.plugins.hoster.FileStoreComUa.class,
jd.plugins.hoster.FileSwapCom.class,
jd.plugins.hoster.FileToBoxCom.class,
jd.plugins.hoster.FileToLinkCom.class,
jd.plugins.hoster.FileTripNet.class,
jd.plugins.hoster.FileUploadDotnet.class,
jd.plugins.hoster.FileViceCom.class,
// jd.plugins.hoster.FileWeCom.class,
jd.plugins.hoster.FileboxRo.class,
jd.plugins.hoster.FilecoreCoNz.class,
jd.plugins.hoster.FiledapCom.class,
jd.plugins.hoster.FiledropperCom.class,
jd.plugins.hoster.FileniumCom.class,
// jd.plugins.hoster.FileparadoxIn.class,
jd.plugins.hoster.FilerCx.class,
// jd.plugins.hoster.FilerNet.class,
jd.plugins.hoster.FilesABCCom.class,
jd.plugins.hoster.FilesCom.class,
jd.plugins.hoster.FilesFlashCom.class,
jd.plugins.hoster.FilesGwKz.class,
jd.plugins.hoster.FilesHostWs.class,
jd.plugins.hoster.FilesInCom.class,
jd.plugins.hoster.FilesMailRu.class,
jd.plugins.hoster.FilesMonsterCom.class,
jd.plugins.hoster.FilesTo.class,
jd.plugins.hoster.FilestoreTo.class,
jd.plugins.hoster.FilmBildDe.class,
jd.plugins.hoster.FilthyRxCom.class,
jd.plugins.hoster.FinaLoadCom.class,
jd.plugins.hoster.FireGetCom.class,
jd.plugins.hoster.FirstFilesCom.class,
jd.plugins.hoster.FisierulMeuRo.class,
jd.plugins.hoster.FiveFantasticPl.class,
jd.plugins.hoster.FiveIlthyCom.class,
jd.plugins.hoster.FiveSingCom.class,
jd.plugins.hoster.FizyCom.class,
jd.plugins.hoster.FlashVidsOrg.class,
jd.plugins.hoster.FlashxTv.class,
jd.plugins.hoster.FlickrCom.class,
jd.plugins.hoster.FlinzyCom.class,
jd.plugins.hoster.FlowLoadCom.class,
jd.plugins.hoster.FourDownFilesCom.class,
jd.plugins.hoster.FourHundredDiskCom.class,
jd.plugins.hoster.FourPlayersDe.class,
// jd.plugins.hoster.FourSaveFileCom.class,
jd.plugins.hoster.FourShareWs.class,
// jd.plugins.hoster.FourSharedCom.class,
jd.plugins.hoster.FourSyncCom.class,
jd.plugins.hoster.FourTubeCom.class,
jd.plugins.hoster.FourUpMe.class,
jd.plugins.hoster.FoxPlayInfo.class,
jd.plugins.hoster.FoxiShareCom.class,
jd.plugins.hoster.Freaksharenet.class,
jd.plugins.hoster.Free18Net.class,
jd.plugins.hoster.FreeBeatDe.class,
jd.plugins.hoster.FreeDiscPl.class,
jd.plugins.hoster.FreeFuckVidzCom.class,
jd.plugins.hoster.FreeHostinaCom.class,
jd.plugins.hoster.FreePornTo.class,
jd.plugins.hoster.FreeShareRu.class,
jd.plugins.hoster.FreeSpaceBy.class,
jd.plugins.hoster.FreeUploadingCom.class,
jd.plugins.hoster.FreeUploadsFr.class,
jd.plugins.hoster.FreeViewMoviesCom.class,
// jd.plugins.hoster.FreeWayMe.class,
// jd.plugins.hoster.FreeWayMeContainer.class,
jd.plugins.hoster.FreecasterTv.class,
jd.plugins.hoster.FsakuraCom.class,
jd.plugins.hoster.FsiShareCom.class,
jd.plugins.hoster.Ftp.class,
jd.plugins.hoster.FuckVidsCom.class,
jd.plugins.hoster.FujiFileMe.class,
jd.plugins.hoster.FunOnlyNet.class,
jd.plugins.hoster.FunVidsOrg.class,
jd.plugins.hoster.FurkNet.class,
jd.plugins.hoster.FuxCom.class,
jd.plugins.hoster.GalaxyFileCom.class,
jd.plugins.hoster.GameFrontCom.class,
jd.plugins.hoster.GameOneDe.class,
jd.plugins.hoster.GameTrailersCom.class,
jd.plugins.hoster.GamesReveurDe.class,
jd.plugins.hoster.GayTubeCom.class,
jd.plugins.hoster.GeTt.class,
jd.plugins.hoster.GetZillaNet.class,
jd.plugins.hoster.GettyFileRu.class,
jd.plugins.hoster.GfsSexCom.class,
jd.plugins.hoster.GigFilesNet.class,
jd.plugins.hoster.GigaBaseCom.class,
jd.plugins.hoster.GigaFileUploadCom.class,
jd.plugins.hoster.GigaFrontDe.class,
jd.plugins.hoster.GigaPetaCom.class,
jd.plugins.hoster.GigaSizeCom.class,
jd.plugins.hoster.GigaUpFr.class,
jd.plugins.hoster.GigabyteUploadCom.class,
jd.plugins.hoster.GirlShareRo.class,
jd.plugins.hoster.GitHubCom.class,
jd.plugins.hoster.GoEarCom.class,
jd.plugins.hoster.GoKuaiCom.class,
jd.plugins.hoster.GogoAnimeCom.class,
// jd.plugins.hoster.GoldBytezCom.class,
jd.plugins.hoster.GooIm.class,
jd.plugins.hoster.GoogleBooks.class,
jd.plugins.hoster.GoogleGroups.class,
// jd.plugins.hoster.GorillaVidIn.class,
jd.plugins.hoster.GrabItShareCom.class,
jd.plugins.hoster.GreenOtrCAt.class,
jd.plugins.hoster.GriftHostCom.class,
jd.plugins.hoster.GrooveSharingCom.class,
jd.plugins.hoster.GrooveShark.class,
jd.plugins.hoster.GrouPs.class,
// jd.plugins.hoster.GuizmoDlNet.class,
jd.plugins.hoster.GulfUpCom.class,
jd.plugins.hoster.GuploadBiz.class,
jd.plugins.hoster.H2PornCom.class,
jd.plugins.hoster.HaberaCom.class,
jd.plugins.hoster.HardSexTubeCom.class,
jd.plugins.hoster.HardwareClipsCom.class,
jd.plugins.hoster.HastaTeamComHoster.class,
jd.plugins.hoster.HdPussyXxx.class,
jd.plugins.hoster.HddSpaceCom.class,
jd.plugins.hoster.HddTomskRu.class,
jd.plugins.hoster.HdmekaniCom.class,
jd.plugins.hoster.Heaven666Org.class,
jd.plugins.hoster.HeavyRCom.class,
jd.plugins.hoster.HeiseDeVideo.class,
jd.plugins.hoster.HellShareCom.class,
jd.plugins.hoster.HellUploadCom.class,
jd.plugins.hoster.HenchFileCom.class,
jd.plugins.hoster.HeroshCom.class,
jd.plugins.hoster.HexUploadCom.class,
jd.plugins.hoster.HideMyAssCom.class,
// jd.plugins.hoster.HipFileCom.class,
jd.plugins.hoster.HippoHostedCom.class,
jd.plugins.hoster.HitBoxTv.class,
jd.plugins.hoster.HitFileNet.class,
jd.plugins.hoster.HomeMoviesTubeCom.class,
jd.plugins.hoster.HomerjDe.class,
jd.plugins.hoster.HornOxeCom.class,
jd.plugins.hoster.Host4DesiCom.class,
jd.plugins.hoster.HostHackerboxOrg.class,
jd.plugins.hoster.HostUjeNet.class,
jd.plugins.hoster.HostingBulkCom.class,
jd.plugins.hoster.HostingcupCom.class,
jd.plugins.hoster.HostinooCom.class,
jd.plugins.hoster.HostsVideosCom.class,
jd.plugins.hoster.HotGooCom.class,
jd.plugins.hoster.HotShagCom.class,
jd.plugins.hoster.HotTeraCom.class,
jd.plugins.hoster.HowFileCom.class,
jd.plugins.hoster.HqMirrorDe.class,
// jd.plugins.hoster.HugeFilesNet.class,
// jd.plugins.hoster.HulkFileCom.class,
// jd.plugins.hoster.HulkLoadCom.class,
jd.plugins.hoster.HulkShareCom.class,
jd.plugins.hoster.HuluCom.class,
jd.plugins.hoster.HundredSixteeThreeDiskCom.class,
jd.plugins.hoster.HundredTwentySexDiskCom.class,
jd.plugins.hoster.HyShareCom.class,
jd.plugins.hoster.HyperFileShareCom.class,
jd.plugins.hoster.IBonerCom.class,
jd.plugins.hoster.IDriveSyncCom.class,
jd.plugins.hoster.IFileHostingNet.class,
jd.plugins.hoster.IFileIt.class,
jd.plugins.hoster.IFilezCom.class,
// jd.plugins.hoster.IGetFileCom.class,
// jd.plugins.hoster.ISaveLinkCom.class,
jd.plugins.hoster.IShareUploadCom.class,
jd.plugins.hoster.IdupIn.class,
jd.plugins.hoster.IfolderRu.class,
jd.plugins.hoster.ImDbCom.class,
jd.plugins.hoster.ImXdNet.class,
jd.plugins.hoster.ImageFap.class,
jd.plugins.hoster.ImageHavenNet.class,
jd.plugins.hoster.ImageNetzDe.class,
jd.plugins.hoster.ImagePorterCom.class,
jd.plugins.hoster.ImageVenueCom.class,
jd.plugins.hoster.ImagesHackUs.class,
jd.plugins.hoster.ImgAhCom.class,
jd.plugins.hoster.ImgBabesCom.class,
jd.plugins.hoster.ImgBarNet.class,
jd.plugins.hoster.ImgDinoCom.class,
jd.plugins.hoster.ImgSpiceCom.class,
jd.plugins.hoster.ImgSrcRu.class,
jd.plugins.hoster.ImgTigerCom.class,
jd.plugins.hoster.ImgUrCom.class,
jd.plugins.hoster.InboxLv.class,
jd.plugins.hoster.IndianPornVideosCom.class,
jd.plugins.hoster.Indowebster.class,
jd.plugins.hoster.InstaGramCom.class,
// jd.plugins.hoster.InterFileNet.class,
jd.plugins.hoster.IperUploadCom.class,
jd.plugins.hoster.Iplus4UCom.class,
jd.plugins.hoster.IshareIaskSinaComCn.class,
jd.plugins.hoster.IssuuCom.class,
jd.plugins.hoster.IzleSeneCom.class,
jd.plugins.hoster.JamendoCom.class,
jd.plugins.hoster.JippyShareCom.class,
jd.plugins.hoster.JizzBoxCom.class,
jd.plugins.hoster.JizzHutCom.class,
jd.plugins.hoster.JoggsCom.class,
jd.plugins.hoster.JoinFileCom.class,
// jd.plugins.hoster.JumboFilesCC.class,
jd.plugins.hoster.JumboFilesCom.class,
jd.plugins.hoster.JumboFilesOrg.class,
// jd.plugins.hoster.JunoCloudMe.class,
jd.plugins.hoster.JustinTv.class,
jd.plugins.hoster.KFilesKz.class,
jd.plugins.hoster.KaraDownloadsCom.class,
jd.plugins.hoster.KatzFilesCom.class,
// jd.plugins.hoster.Keep2ShareCc.class,
jd.plugins.hoster.KeepShareNet.class,
jd.plugins.hoster.KeezMoviesCom.class,
// jd.plugins.hoster.KingFilesNet.class,
jd.plugins.hoster.KingShareTo.class,
jd.plugins.hoster.Kiwi6Com.class,
// jd.plugins.hoster.KooFileCom.class,
jd.plugins.hoster.L4dMapsCom.class,
jd.plugins.hoster.LaFileCom.class,
jd.plugins.hoster.LaFilesCom.class,
jd.plugins.hoster.LacoquiNet.class,
jd.plugins.hoster.LajusangatNet.class,
// jd.plugins.hoster.LalataInfo.class,
jd.plugins.hoster.LaoUploadCom.class,
jd.plugins.hoster.LarasLevelBaseOrg.class,
// jd.plugins.hoster.LemUploadsCom.class,
// jd.plugins.hoster.LetitBitNet.class,
jd.plugins.hoster.LetitbitTv.class,
jd.plugins.hoster.LibGenInfo.class,
jd.plugins.hoster.LikeUploadNet.class,
jd.plugins.hoster.LimeVideoNet.class,
jd.plugins.hoster.LinkFileDe.class,
jd.plugins.hoster.LinkSnappyCom.class,
jd.plugins.hoster.LinkzHostCom.class,
// jd.plugins.hoster.LiveCloudzCom.class,
jd.plugins.hoster.LiveDriveCom.class,
jd.plugins.hoster.LiveLeakCom.class,
jd.plugins.hoster.LiveMixTapesCom.class,
jd.plugins.hoster.LoadGatorCom.class,
jd.plugins.hoster.LoadTo.class,
jd.plugins.hoster.LocalHostrCom.class,
jd.plugins.hoster.LolaBitsEs.class,
// jd.plugins.hoster.LomaFileCom.class,
jd.plugins.hoster.LongFilesCom.class,
jd.plugins.hoster.LooMboCom.class,
jd.plugins.hoster.LoudUploadCom.class,
// jd.plugins.hoster.LoveVideoTv.class,
jd.plugins.hoster.LuckyShareNet.class,
// jd.plugins.hoster.LumFileCom.class,
jd.plugins.hoster.LunaticFilesCom.class,
jd.plugins.hoster.LyndaCom.class,
jd.plugins.hoster.MadThumbsCom.class,
jd.plugins.hoster.MadeVidCom.class,
jd.plugins.hoster.MagnoVideoCom.class,
jd.plugins.hoster.MaisMe.class,
jd.plugins.hoster.MaisUolComBr.class,
jd.plugins.hoster.MakinaManiaCom.class,
jd.plugins.hoster.MammutMailCom.class,
jd.plugins.hoster.MangaTradersCom.class,
jd.plugins.hoster.Mangastream.class,
// jd.plugins.hoster.MaskFileCom.class,
jd.plugins.hoster.MaxSharePl.class,
jd.plugins.hoster.MaxVideoPl.class,
jd.plugins.hoster.MaximusUploadCom.class,
jd.plugins.hoster.McUploadCom.class,
// jd.plugins.hoster.MedOneFire.class,
// jd.plugins.hoster.MediaFileStorageNet.class,
// jd.plugins.hoster.MediaFireBz.class,
// jd.plugins.hoster.MediaOneFileCom.class,
jd.plugins.hoster.MediaValiseCom.class,
jd.plugins.hoster.MediafireCom.class,
jd.plugins.hoster.MegaCacheNet.class,
jd.plugins.hoster.MegaCloudCom.class,
jd.plugins.hoster.MegaConz.class,
jd.plugins.hoster.MegaCrypterCom.class,
jd.plugins.hoster.MegaDebridEu.class,
jd.plugins.hoster.MegaFileUploadCom.class,
// jd.plugins.hoster.MegaFilesSe.class,
jd.plugins.hoster.MegaIronNet.class,
jd.plugins.hoster.MegaOtrDe.class,
// jd.plugins.hoster.MegaReleaseOrg.class,
jd.plugins.hoster.MegaShareBy.class,
jd.plugins.hoster.MegaUlCom.class,
jd.plugins.hoster.MegaUpDownCom.class,
jd.plugins.hoster.MegaVideozEu.class,
jd.plugins.hoster.MegaYoupornCc.class,
jd.plugins.hoster.MegasharesCom.class,
jd.plugins.hoster.MegaszafaCom.class,
jd.plugins.hoster.MejubaCom.class,
jd.plugins.hoster.MeoCloudPt.class,
jd.plugins.hoster.MetArtCom.class,
jd.plugins.hoster.MetFilesCom.class,
jd.plugins.hoster.MetacafeCom.class,
jd.plugins.hoster.MicrosoftCom.class,
jd.plugins.hoster.MidUploadCom.class,
jd.plugins.hoster.MigaLoadCom.class,
// jd.plugins.hoster.MightyUploadCom.class,
jd.plugins.hoster.MijnBestandNl.class,
jd.plugins.hoster.MiloShareCom.class,
jd.plugins.hoster.MiloyskiCom.class,
jd.plugins.hoster.MinUs.class,
jd.plugins.hoster.MinhatecaComBr.class,
jd.plugins.hoster.MinoShareCom.class,
jd.plugins.hoster.MirrorVerbundCom.class,
jd.plugins.hoster.MixSharedCom.class,
jd.plugins.hoster.MixUploadOrg.class,
jd.plugins.hoster.MixtureCloudCom.class,
jd.plugins.hoster.MkxkCom.class,
jd.plugins.hoster.MlFat4ArabCom.class,
jd.plugins.hoster.ModDbCom.class,
jd.plugins.hoster.MoeVideosNet.class,
jd.plugins.hoster.MofoSexCom.class,
jd.plugins.hoster.MoiDiskRu.class,
jd.plugins.hoster.MojeVideoSk.class,
jd.plugins.hoster.MojoLoadCom.class,
jd.plugins.hoster.MooShareBiz.class,
jd.plugins.hoster.MotherLessCom.class,
jd.plugins.hoster.MountFileNet.class,
jd.plugins.hoster.MovDivxCom.class,
jd.plugins.hoster.MovPodIn.class,
jd.plugins.hoster.MovReelCom.class,
jd.plugins.hoster.MovShareNet.class,
jd.plugins.hoster.MovieFapCom.class,
jd.plugins.hoster.MovieSandCom.class,
jd.plugins.hoster.MovikiRu.class,
jd.plugins.hoster.Mp3HamsterNet.class,
jd.plugins.hoster.Mp3TheNet.class,
jd.plugins.hoster.Mp4UploadCom.class,
jd.plugins.hoster.MrmkvFileshareCom.class,
// jd.plugins.hoster.MuchShareNet.class,
jd.plugins.hoster.MultiDebridCom.class,
jd.plugins.hoster.MultiShareCz.class,
jd.plugins.hoster.MultiUploadNlDirect.class,
jd.plugins.hoster.MultidownCoIl.class,
jd.plugins.hoster.MultihostersCom.class,
jd.plugins.hoster.MusickapozSe.class,
jd.plugins.hoster.MxuaCom.class,
jd.plugins.hoster.MyDiscNet.class,
jd.plugins.hoster.MyDiskGe.class,
jd.plugins.hoster.MyDownloaderNet.class,
jd.plugins.hoster.MyDriveCom.class,
jd.plugins.hoster.MyGirlfriendPornCom.class,
jd.plugins.hoster.MyGirlfriendsVidsNet.class,
jd.plugins.hoster.MyJizzTubeCom.class,
jd.plugins.hoster.MyMailRu.class,
jd.plugins.hoster.MySpassDe.class,
jd.plugins.hoster.MyStoreTo.class,
jd.plugins.hoster.MyUplBoxCom.class,
jd.plugins.hoster.MyVideo.class,
jd.plugins.hoster.MyXvidsCom.class,
jd.plugins.hoster.MymediaYamCom.class,
jd.plugins.hoster.MystereTvCom.class,
jd.plugins.hoster.MyuploadDK.class,
jd.plugins.hoster.N24Mediathek.class,
jd.plugins.hoster.NFormationNet.class,
jd.plugins.hoster.NRomsDe.class,
jd.plugins.hoster.NakidoCom.class,
jd.plugins.hoster.NarodRu.class,
jd.plugins.hoster.NaszaKlasa.class,
jd.plugins.hoster.NekakaCom.class,
jd.plugins.hoster.NetKupsCom.class,
// jd.plugins.hoster.Netloadin.class,
jd.plugins.hoster.NewGamexCom.class,
jd.plugins.hoster.NicoVideoJp.class,
jd.plugins.hoster.NitroBitsCom.class,
// jd.plugins.hoster.NoPremiumPl.class,
jd.plugins.hoster.NoelShareCom.class,
jd.plugins.hoster.NornarCom.class,
jd.plugins.hoster.NosUploadCom.class,
jd.plugins.hoster.NosVideoCom.class,
jd.plugins.hoster.NovaFileCom.class,
jd.plugins.hoster.NovaMovMe.class,
jd.plugins.hoster.NovaUpMovcom.class,
jd.plugins.hoster.NowDownloadEu.class,
jd.plugins.hoster.NowVideoEu.class,
jd.plugins.hoster.NowVideoWs.class,
jd.plugins.hoster.NowVideosEu.class,
jd.plugins.hoster.NtUploadCom.class,
jd.plugins.hoster.NuVidCom.class,
jd.plugins.hoster.NzbLoadCom.class,
// jd.plugins.hoster.OBoomCom.class,
jd.plugins.hoster.ORFMediathek.class,
jd.plugins.hoster.ObligaoCom.class,
jd.plugins.hoster.Oceanus.class,
jd.plugins.hoster.OdiMusicNet.class,
jd.plugins.hoster.Offline.class,
jd.plugins.hoster.OleUpCom.class,
jd.plugins.hoster.OlgetCom.class,
jd.plugins.hoster.OmpanCom.class,
jd.plugins.hoster.OneDriveLiveCom.class,
// jd.plugins.hoster.OneEightZeroUploadCom.class,
jd.plugins.hoster.OneFichierCom.class,
jd.plugins.hoster.OneHundredNineteenGCom.class,
jd.plugins.hoster.OneMillionFilesCom.class,
jd.plugins.hoster.OneThousandEbCom.class,
jd.plugins.hoster.OneTpanCom.class,
jd.plugins.hoster.OneTwoThreeVideoNl.class,
jd.plugins.hoster.OnethousandSharedCom.class,
jd.plugins.hoster.OnlineNoLifeTvCom.class,
jd.plugins.hoster.OnlineTvRecorderCom.class,
jd.plugins.hoster.OpenDriveCom.class,
jd.plugins.hoster.OpenSubtitlesOrg.class,
jd.plugins.hoster.OrangeFilesMe.class,
jd.plugins.hoster.OrgasmCom.class,
// jd.plugins.hoster.OrtoFilesCom.class,
jd.plugins.hoster.OsUpCom.class,
jd.plugins.hoster.OsuYasOnlineNet.class,
jd.plugins.hoster.OtrDatenkellerAt.class,
jd.plugins.hoster.OtrDownloadDe.class,
jd.plugins.hoster.OtrFilesDe.class,
jd.plugins.hoster.OverLoadMe.class,
jd.plugins.hoster.OverThumbsCom.class,
jd.plugins.hoster.PCloudCom.class,
jd.plugins.hoster.PackUploadCom.class,
jd.plugins.hoster.PanBaiduCom.class,
jd.plugins.hoster.PandamemoCom.class,
jd.plugins.hoster.PandoraTV.class,
jd.plugins.hoster.ParelliSavvyClubCom.class,
jd.plugins.hoster.PartageFacileCom.class,
jd.plugins.hoster.PcWeltDe.class,
jd.plugins.hoster.PdfCastOrg.class,
jd.plugins.hoster.PerfectGirlsNet.class,
jd.plugins.hoster.PervClipsCom.class,
jd.plugins.hoster.PhotoShareRu.class,
jd.plugins.hoster.PivitLoad.class,
jd.plugins.hoster.PixRouteCom.class,
jd.plugins.hoster.PizzaUploadCom.class,
jd.plugins.hoster.PlayFm.class,
jd.plugins.hoster.PlayFourtyFourNet.class,
jd.plugins.hoster.PlayRapportSe.class,
jd.plugins.hoster.PlayVidCom.class,
jd.plugins.hoster.PlayedTo.class,
jd.plugins.hoster.PliczekNet.class,
jd.plugins.hoster.PlikusPl.class,
jd.plugins.hoster.PlunderCom.class,
jd.plugins.hoster.PornCom.class,
jd.plugins.hoster.PornHostCom.class,
jd.plugins.hoster.PornHubCom.class,
jd.plugins.hoster.PornOxoCom.class,
jd.plugins.hoster.PornRabbitCom.class,
jd.plugins.hoster.PornStarNetworkCom.class,
jd.plugins.hoster.PornTo.class,
jd.plugins.hoster.PornTubeCom.class,
jd.plugins.hoster.PornUpMe.class,
jd.plugins.hoster.PornYeahCom.class,
jd.plugins.hoster.PornativeCom.class,
jd.plugins.hoster.PornerBrosCom.class,
jd.plugins.hoster.PornperCom.class,
// jd.plugins.hoster.PotLoadCom.class,
// jd.plugins.hoster.PowVideoNet.class,
jd.plugins.hoster.PreFilesCom.class,
jd.plugins.hoster.PremiumDebridCom.class,
jd.plugins.hoster.PremiumTo.class,
jd.plugins.hoster.PremiumaxNet.class,
jd.plugins.hoster.PremiumizeMe.class,
jd.plugins.hoster.PremiunsOrg.class,
jd.plugins.hoster.PresstvIr.class,
jd.plugins.hoster.PrimeMusicRu.class,
jd.plugins.hoster.PrimePhileCom.class,
jd.plugins.hoster.PrimeShareTv.class,
jd.plugins.hoster.PrivateHomeClipsCom.class,
jd.plugins.hoster.ProSevenDe.class,
// jd.plugins.hoster.ProTransTechBvNetwork.class,
// jd.plugins.hoster.ProjectFreeUploadCom.class,
jd.plugins.hoster.PromptFileCom.class,
jd.plugins.hoster.Przeslijnet.class,
jd.plugins.hoster.Ps3GameRoomNet.class,
jd.plugins.hoster.PureVidCom.class,
jd.plugins.hoster.PurevolumeCom.class,
jd.plugins.hoster.PutDriveCom.class,
jd.plugins.hoster.PutIO.class,
jd.plugins.hoster.PutLockerCom.class,
jd.plugins.hoster.PutMeOrg.class,
jd.plugins.hoster.PutlockerWs.class,
jd.plugins.hoster.QJNet.class,
jd.plugins.hoster.QKupNet.class,
jd.plugins.hoster.QiannaoCom.class,
jd.plugins.hoster.QqCom.class,
jd.plugins.hoster.QtyFilesCom.class,
// jd.plugins.hoster.QueenShareCom.class,
jd.plugins.hoster.QuickShareCz.class,
jd.plugins.hoster.QuickUploadDotNet.class,
jd.plugins.hoster.RGhostRu.class,
jd.plugins.hoster.RPNetBiz.class,
jd.plugins.hoster.RTL2De.class,
jd.plugins.hoster.RTLnowDe.class,
jd.plugins.hoster.RTMPDownload.class,
jd.plugins.hoster.RabitFilesCom.class,
jd.plugins.hoster.RapidFileShareNet.class,
// jd.plugins.hoster.RapidGatorNet.class,
jd.plugins.hoster.RapidShareRu.class,
jd.plugins.hoster.RapidStationCom.class,
// jd.plugins.hoster.RapidStoneCom.class,
jd.plugins.hoster.RapidVideoTv.class,
jd.plugins.hoster.Rapids24Pl.class,
jd.plugins.hoster.RapidsPl.class,
jd.plugins.hoster.Rapidshare.class,
jd.plugins.hoster.RapiduNet.class,
jd.plugins.hoster.RareFileNet.class,
jd.plugins.hoster.RaviShareCom.class,
jd.plugins.hoster.RayFileCom.class,
// jd.plugins.hoster.RdFsCom.class,
// jd.plugins.hoster.RealDebridCom.class,
jd.plugins.hoster.RealGfPornCom.class,
jd.plugins.hoster.RealityKingsCom.class,
jd.plugins.hoster.RedBunkerNet.class,
// jd.plugins.hoster.RedLoadNet.class,
jd.plugins.hoster.RedTubeCom.class,
jd.plugins.hoster.RehostTo.class,
jd.plugins.hoster.RemixShareCom.class,
jd.plugins.hoster.ReplikPl.class,
jd.plugins.hoster.RestFileCom.class,
jd.plugins.hoster.ReverBnationComHoster.class,
jd.plugins.hoster.RioUploadCom.class,
jd.plugins.hoster.RiotShareCom.class,
jd.plugins.hoster.RnbLoadCom.class,
// jd.plugins.hoster.RockDizFileCom.class,
jd.plugins.hoster.RocketFilesNet.class,
jd.plugins.hoster.RodFileCom.class,
jd.plugins.hoster.RomHustlerNet.class,
jd.plugins.hoster.RomsZopharNet.class,
jd.plugins.hoster.RoyalVidsEu.class,
jd.plugins.hoster.RtveEs.class,
jd.plugins.hoster.RuTubeRu.class,
jd.plugins.hoster.RufoxRu.class,
// jd.plugins.hoster.RyuShareCom.class,
jd.plugins.hoster.SafaShareCom.class,
jd.plugins.hoster.SafeSharingEu.class,
jd.plugins.hoster.SaganFilesCom.class,
// jd.plugins.hoster.SaleFilesCom.class,
jd.plugins.hoster.SamePageIo.class,
// jd.plugins.hoster.SanShareCom.class,
jd.plugins.hoster.SaryShareCom.class,
// jd.plugins.hoster.SaveTv.class,
jd.plugins.hoster.ScribdCom.class,
jd.plugins.hoster.SecureUploadEu.class,
jd.plugins.hoster.SendFaileCom.class,
jd.plugins.hoster.SendFilePl.class,
jd.plugins.hoster.SendFileSu.class,
jd.plugins.hoster.SendFilesNl.class,
jd.plugins.hoster.SendMyWayCom.class,
jd.plugins.hoster.SendSpacePl.class,
jd.plugins.hoster.SendspaceCom.class,
jd.plugins.hoster.SenseLessTv.class,
jd.plugins.hoster.SevenNineFiveEightCom.class,
jd.plugins.hoster.SevenTwoDjCom.class,
jd.plugins.hoster.SevenloadCom.class,
jd.plugins.hoster.SexSeeVideoNet.class,
jd.plugins.hoster.SexZindianCom.class,
jd.plugins.hoster.SexyAndFunnyCom.class,
jd.plugins.hoster.SfShareSe.class,
jd.plugins.hoster.ShaHidMbcNet.class,
jd.plugins.hoster.ShantiBitCom.class,
jd.plugins.hoster.Share4WebCom.class,
jd.plugins.hoster.Share50Com.class,
jd.plugins.hoster.ShareBeastCom.class,
// jd.plugins.hoster.ShareBlueEu.class,
jd.plugins.hoster.ShareByteNet.class,
jd.plugins.hoster.ShareDirCom.class,
jd.plugins.hoster.ShareFlareNet.class,
jd.plugins.hoster.ShareGadgetCom.class,
jd.plugins.hoster.ShareLinkLi.class,
jd.plugins.hoster.ShareNeoNet.class,
// jd.plugins.hoster.ShareOnlineBiz.class,
// jd.plugins.hoster.ShareProfiCom.class,
jd.plugins.hoster.ShareRapidCz.class,
jd.plugins.hoster.ShareRepoCom.class,
jd.plugins.hoster.ShareSendCom.class,
// jd.plugins.hoster.ShareSixCom.class,
jd.plugins.hoster.ShareSixNet.class,
jd.plugins.hoster.ShareSwiftCom.class,
jd.plugins.hoster.ShareXXpgComBr.class,
jd.plugins.hoster.ShareYourFileBiz.class,
jd.plugins.hoster.SharecashDotOrg2.class,
jd.plugins.hoster.SharedCom.class,
jd.plugins.hoster.SharedSx.class,
jd.plugins.hoster.Shareplacecom.class,
// jd.plugins.hoster.SharingMasterCom.class,
jd.plugins.hoster.ShesFreakyCom.class,
jd.plugins.hoster.ShurLoadEs.class,
jd.plugins.hoster.ShutterStockCom.class,
jd.plugins.hoster.SimpleShareOrg.class,
jd.plugins.hoster.SimplyDebridCom.class,
// jd.plugins.hoster.SimplyPremiumCom.class,
// jd.plugins.hoster.SinhroNet.class,
// jd.plugins.hoster.SizFileCom.class,
jd.plugins.hoster.SkyGlobeRu.class,
jd.plugins.hoster.SlideShareNet.class,
jd.plugins.hoster.SlingFileCom.class,
jd.plugins.hoster.SloozieCom.class,
jd.plugins.hoster.SlutLoadCom.class,
jd.plugins.hoster.SmotriCom.class,
jd.plugins.hoster.SnotrCom.class,
jd.plugins.hoster.SociFilesCom.class,
jd.plugins.hoster.SockShareCom.class,
jd.plugins.hoster.SockShareWs.class,
jd.plugins.hoster.SoftPediaCom.class,
jd.plugins.hoster.SolidFilesCom.class,
jd.plugins.hoster.SongsTo.class,
jd.plugins.hoster.SosodoCom.class,
jd.plugins.hoster.SoundClickCom.class,
jd.plugins.hoster.SoundOwlCom.class,
jd.plugins.hoster.SoundSnapCom.class,
jd.plugins.hoster.SoundcloudCom.class,
jd.plugins.hoster.SpaadyShareCom.class,
jd.plugins.hoster.Space4FileCom.class,
jd.plugins.hoster.SpaceForFilesCom.class,
jd.plugins.hoster.SpankBangCom.class,
jd.plugins.hoster.SpankWireCom.class,
jd.plugins.hoster.SpeedShareEu.class,
jd.plugins.hoster.SpeedoShareCom.class,
jd.plugins.hoster.SpeedyShareCom.class,
jd.plugins.hoster.Speedy_ShareCom.class,
jd.plugins.hoster.SpicyFileCom.class,
jd.plugins.hoster.SpiegelDe.class,
jd.plugins.hoster.StaSh.class,
jd.plugins.hoster.StageFlvCom.class,
jd.plugins.hoster.StageVuCom.class,
jd.plugins.hoster.StahovadloCz.class,
jd.plugins.hoster.StiahniSi.class,
jd.plugins.hoster.StileProjectCom.class,
jd.plugins.hoster.StooorageCom.class,
// jd.plugins.hoster.StoragelyCom.class,
jd.plugins.hoster.StorePlaceOrg.class,
jd.plugins.hoster.StreamCloudEu.class,
jd.plugins.hoster.StreamManiaCom.class,
// jd.plugins.hoster.StreamRatioCom.class,
jd.plugins.hoster.StreaminTo.class,
jd.plugins.hoster.SubSceneCom.class,
// jd.plugins.hoster.SubeMe.class,
jd.plugins.hoster.SubmitYourFlicksCom.class,
jd.plugins.hoster.SubmitYourTapesCom.class,
jd.plugins.hoster.SugarSyncCom.class,
jd.plugins.hoster.SunPornoCom.class,
jd.plugins.hoster.SuperHqPornCom.class,
jd.plugins.hoster.SuperLoadCz.class,
jd.plugins.hoster.SuperSharePl.class,
jd.plugins.hoster.SuperUploadCom.class,
// jd.plugins.hoster.SwankShareCom.class,
jd.plugins.hoster.SwatUploadCom.class,
jd.plugins.hoster.SwoopshareCom.class,
jd.plugins.hoster.TapeTv.class,
jd.plugins.hoster.Tb7Pl.class,
jd.plugins.hoster.TedCom.class,
jd.plugins.hoster.TeleFiveDe.class,
jd.plugins.hoster.TempFileRu.class,
jd.plugins.hoster.TempShareCom.class,
jd.plugins.hoster.TenFilesCom.class,
// jd.plugins.hoster.TeraFileCo.class,
jd.plugins.hoster.TgfServicesCom.class,
jd.plugins.hoster.ThaiCyberUploadCom.class,
jd.plugins.hoster.TheAmateurZoneInfo.class,
jd.plugins.hoster.TheFileBayCom.class,
jd.plugins.hoster.TheFileMe.class,
jd.plugins.hoster.TheFileUploadCom.class,
jd.plugins.hoster.ThousandTwentyFourDiskCom.class,
jd.plugins.hoster.ThreeADiskCom.class,
// jd.plugins.hoster.TiShareCom.class,
jd.plugins.hoster.TimSahCom.class,
jd.plugins.hoster.TmzCom.class,
jd.plugins.hoster.TnaFlixCom.class,
jd.plugins.hoster.TokyoTubeCom.class,
jd.plugins.hoster.TomWansCom.class,
jd.plugins.hoster.ToukouCityTo.class,
jd.plugins.hoster.ToutCom.class,
jd.plugins.hoster.ToyPicsNet.class,
jd.plugins.hoster.TradingPornCom.class,
jd.plugins.hoster.TrailerAddictCom.class,
jd.plugins.hoster.TrailersAppleCom.class,
jd.plugins.hoster.TransitFilesCom.class,
// jd.plugins.hoster.TreeFilesCom.class,
jd.plugins.hoster.TriLuLiLuRo.class,
jd.plugins.hoster.TrillHDCom.class,
jd.plugins.hoster.TropicShareCom.class,
jd.plugins.hoster.TuDouCom.class,
jd.plugins.hoster.TuTv.class,
jd.plugins.hoster.Tube8Com.class,
jd.plugins.hoster.TubeCloudNet.class,
jd.plugins.hoster.TubeSssCom.class,
jd.plugins.hoster.TubeWolfCom.class,
jd.plugins.hoster.TubeqNet.class,
jd.plugins.hoster.TumblrCom.class,
jd.plugins.hoster.TumiTv.class,
jd.plugins.hoster.TuneScoopCom.class,
jd.plugins.hoster.TurbixPl.class,
// jd.plugins.hoster.TurboBitNet.class,
jd.plugins.hoster.TurboTransferPl.class,
jd.plugins.hoster.TurkcealtyaziOrg.class,
// jd.plugins.hoster.TusFilesNet.class,
jd.plugins.hoster.TuxFileCom.class,
jd.plugins.hoster.TvSmeSk.class,
jd.plugins.hoster.TviIolPt.class,
jd.plugins.hoster.TwisTysCom.class,
jd.plugins.hoster.TwitVidCom.class,
jd.plugins.hoster.TwoDownloadDe.class,
jd.plugins.hoster.TwoDownloadzCom.class,
jd.plugins.hoster.TwoGbHostingCom.class,
jd.plugins.hoster.TwoHundredTwentyRo.class,
jd.plugins.hoster.TwoSharedCom.class,
jd.plugins.hoster.TwoUpfileCom.class,
jd.plugins.hoster.TwojLimitPl.class,
jd.plugins.hoster.TyzdenSk.class,
jd.plugins.hoster.U115Com.class,
jd.plugins.hoster.UFileEu.class,
jd.plugins.hoster.UFileNet.class,
jd.plugins.hoster.UGoUploadNet.class,
jd.plugins.hoster.UTubeRu.class,
jd.plugins.hoster.UaFileCom.class,
jd.plugins.hoster.UflashTv.class,
jd.plugins.hoster.UitzendinggemistNl.class,
jd.plugins.hoster.UlmenTv.class,
jd.plugins.hoster.UlozTo.class,
jd.plugins.hoster.UloziskoSk.class,
jd.plugins.hoster.UltraMegaBitCom.class,
jd.plugins.hoster.UltraShareNet.class,
jd.plugins.hoster.UlubPl.class,
jd.plugins.hoster.UnLimitCoIl.class,
jd.plugins.hoster.UncappedDownloadsCom.class,
jd.plugins.hoster.UniBytesCom.class,
jd.plugins.hoster.UnlimitZoneCom.class,
jd.plugins.hoster.UnrestrictLi.class,
jd.plugins.hoster.Up09Com.class,
jd.plugins.hoster.Up4ShareVn.class,
jd.plugins.hoster.UpBrasilInfo.class,
jd.plugins.hoster.UpDownBz.class,
jd.plugins.hoster.UpFileVn.class,
jd.plugins.hoster.UpHerePl.class,
jd.plugins.hoster.UpMyFilesCom.class,
jd.plugins.hoster.UpNitoSk.class,
jd.plugins.hoster.UpShareMe.class,
jd.plugins.hoster.UpSharedCom.class,
jd.plugins.hoster.UpToBoxCom.class,
jd.plugins.hoster.UpWapRu.class,
jd.plugins.hoster.UpaFileCom.class,
jd.plugins.hoster.UpasiasCom.class,
jd.plugins.hoster.UpchiCoIl.class,
jd.plugins.hoster.UpdateRequiredHostPlugin.class,
jd.plugins.hoster.UpfCoIl.class,
jd.plugins.hoster.UpfileMobi.class,
jd.plugins.hoster.UploaDriveCom.class,
// jd.plugins.hoster.UploadBazCom.class,
jd.plugins.hoster.UploadBlastCom.class,
jd.plugins.hoster.UploadBoyCom.class,
jd.plugins.hoster.UploadCCom.class,
jd.plugins.hoster.UploadComUa.class,
jd.plugins.hoster.UploadDriveCom.class,
jd.plugins.hoster.UploadEe.class,
jd.plugins.hoster.UploadHeroCom.class,
jd.plugins.hoster.UploadHuntCom.class,
jd.plugins.hoster.UploadIlCom.class,
jd.plugins.hoster.UploadIncCom.class,
jd.plugins.hoster.UploadLabCom.class,
jd.plugins.hoster.UploadLuxCom.class,
jd.plugins.hoster.UploadLwCom.class,
jd.plugins.hoster.UploadMbCom.class,
jd.plugins.hoster.UploadNetworkEu.class,
jd.plugins.hoster.UploadRocketNet.class,
jd.plugins.hoster.UploadSatCom.class,
jd.plugins.hoster.UploadSpacePl.class,
jd.plugins.hoster.UploadStube.class,
jd.plugins.hoster.UploadTwoCom.class,
jd.plugins.hoster.UploadURCom.class,
jd.plugins.hoster.UploadZealCom.class,
jd.plugins.hoster.UploadableCh.class,
jd.plugins.hoster.Uploadedto.class,
jd.plugins.hoster.UploaderJp.class,
jd.plugins.hoster.UploadingCom.class,
jd.plugins.hoster.UploadingItCom.class,
jd.plugins.hoster.UploadizerNet.class,
jd.plugins.hoster.UploadsCenterCom.class,
jd.plugins.hoster.UploadsWs.class,
jd.plugins.hoster.UppItCom.class,
jd.plugins.hoster.UpstoRe.class,
jd.plugins.hoster.UsaUplNet.class,
// jd.plugins.hoster.UseFileCom.class,
jd.plugins.hoster.UserPornCom.class,
jd.plugins.hoster.UstreamTv.class,
jd.plugins.hoster.UzManTvCom.class,
jd.plugins.hoster.VKontakteRuHoster.class,
jd.plugins.hoster.VPornCom.class,
jd.plugins.hoster.VPornoTv.class,
// jd.plugins.hoster.VShareEu.class,
jd.plugins.hoster.VddlrCm.class,
jd.plugins.hoster.VdiskCn.class,
jd.plugins.hoster.VeeHdCom.class,
jd.plugins.hoster.VeevrCom.class,
jd.plugins.hoster.VeohCom.class,
// jd.plugins.hoster.VerZendBe.class,
jd.plugins.hoster.VeterokTv.class,
jd.plugins.hoster.Vid2CCom.class,
// jd.plugins.hoster.VidBoxYt.class,
// jd.plugins.hoster.VidBullCom.class,
// jd.plugins.hoster.VidBuxCom.class,
jd.plugins.hoster.VidGrabNet.class,
jd.plugins.hoster.VidHogCom.class,
// jd.plugins.hoster.VidPlayNet.class,
// jd.plugins.hoster.VidSpotNet.class,
// jd.plugins.hoster.VidToMe.class,
jd.plugins.hoster.VidUpMe.class,
jd.plugins.hoster.VidZurCom.class,
jd.plugins.hoster.VidearnCom.class,
jd.plugins.hoster.VideoBamCom.class,
jd.plugins.hoster.VideoBashCom.class,
jd.plugins.hoster.VideoBbCom.class,
jd.plugins.hoster.VideoBoxCom.class,
jd.plugins.hoster.VideoBugNet.class,
jd.plugins.hoster.VideoCnnturkCom.class,
// jd.plugins.hoster.VideoDdNet.class,
jd.plugins.hoster.VideoFCTwoCom.class,
jd.plugins.hoster.VideoFourtyFourNet.class,
jd.plugins.hoster.VideoFunMe.class,
jd.plugins.hoster.VideoGoogle.class,
jd.plugins.hoster.VideoHaberturkCom.class,
jd.plugins.hoster.VideoLogTv.class,
jd.plugins.hoster.VideoMediasetIt.class,
jd.plugins.hoster.VideoMegaTv.class,
jd.plugins.hoster.VideoMsnCom.class,
jd.plugins.hoster.VideoNanCom.class,
// jd.plugins.hoster.VideoNestNet.class,
jd.plugins.hoster.VideoNhlCom.class,
jd.plugins.hoster.VideoNtvMsnbcCom.class,
jd.plugins.hoster.VideoOnlineUa.class,
jd.plugins.hoster.VideoPremiumNet.class,
// jd.plugins.hoster.VideoSlimNet.class,
jd.plugins.hoster.VideoTt.class,
jd.plugins.hoster.VideoWeedCom.class,
jd.plugins.hoster.VideoWoodTv.class,
jd.plugins.hoster.VideoalbumyAzetSk.class,
jd.plugins.hoster.VideolecturesNet.class,
jd.plugins.hoster.VideosSapo.class,
jd.plugins.hoster.VideozedNet.class,
jd.plugins.hoster.VidiVodoCom.class,
jd.plugins.hoster.VidigBiz.class,
jd.plugins.hoster.VidobuCom.class,
jd.plugins.hoster.VidsBz.class,
jd.plugins.hoster.VidsMySpaceCom.class,
jd.plugins.hoster.VidzBeezCom.class,
jd.plugins.hoster.VidziTv.class,
jd.plugins.hoster.ViiSk.class,
jd.plugins.hoster.VimeoCom.class,
jd.plugins.hoster.VineCo.class,
jd.plugins.hoster.Vipfilecom.class,
jd.plugins.hoster.VitaminoGretmenCom.class,
// jd.plugins.hoster.VodLockerCom.class,
jd.plugins.hoster.VoduCh.class,
jd.plugins.hoster.VplayRo.class,
jd.plugins.hoster.VreerCom.class,
jd.plugins.hoster.WDivxCom.class,
jd.plugins.hoster.WallBaseCc.class,
// jd.plugins.hoster.WalloBitCom.class,
jd.plugins.hoster.WatTv.class,
jd.plugins.hoster.WatchFreeInHdCom.class,
jd.plugins.hoster.WatchGfPornCom.class,
jd.plugins.hoster.WdrDeMediathek.class,
jd.plugins.hoster.WeTransferCom.class,
jd.plugins.hoster.WebCamsCom.class,
jd.plugins.hoster.WebDe.class,
jd.plugins.hoster.WebFileHostCom.class,
jd.plugins.hoster.WebShareCz.class,
jd.plugins.hoster.WikiFortioCom.class,
jd.plugins.hoster.WipFilesNet.class,
jd.plugins.hoster.WizUploadCom.class,
jd.plugins.hoster.WordPressTv.class,
jd.plugins.hoster.WorldBytezCom.class,
jd.plugins.hoster.WorldClipsRu.class,
jd.plugins.hoster.WorldSexCom.class,
jd.plugins.hoster.WorldStarAmateursCom.class,
jd.plugins.hoster.WorldStarHipHopCom.class,
jd.plugins.hoster.WrzucTo.class,
jd.plugins.hoster.WrzutaPl.class,
jd.plugins.hoster.WuShareCom.class,
jd.plugins.hoster.WualaCom.class,
jd.plugins.hoster.WunschOtrDe.class,
jd.plugins.hoster.WyslijPlikPl.class,
jd.plugins.hoster.WyslijToPl.class,
jd.plugins.hoster.XArtCom.class,
jd.plugins.hoster.XFileSharingProBasic.class,
jd.plugins.hoster.XHamsterCom.class,
jd.plugins.hoster.XRabbitCom.class,
jd.plugins.hoster.XShareCom.class,
jd.plugins.hoster.XTubeCom.class,
jd.plugins.hoster.XUploadingNet.class,
jd.plugins.hoster.XVideoHostCom.class,
jd.plugins.hoster.XXXAPornCom.class,
jd.plugins.hoster.XaxTubeCom.class,
jd.plugins.hoster.XboxIsoZoneCom.class,
jd.plugins.hoster.XdaDevelopersCom.class,
jd.plugins.hoster.XddiskCom.class,
jd.plugins.hoster.XenuBoxCom.class,
jd.plugins.hoster.XlockerNet.class,
jd.plugins.hoster.XnXxCom.class,
jd.plugins.hoster.XoGoGoCom.class,
jd.plugins.hoster.XunleiCom.class,
jd.plugins.hoster.XupIn.class,
jd.plugins.hoster.XvidStageCom.class,
jd.plugins.hoster.XvidStreamNet.class,
jd.plugins.hoster.XvideosCom.class,
jd.plugins.hoster.XxxKinKyCom.class,
jd.plugins.hoster.YDownloadOrg.class,
jd.plugins.hoster.YahooCom.class,
jd.plugins.hoster.YamiVideoCom.class,
jd.plugins.hoster.YesLoadNet.class,
jd.plugins.hoster.YobtTv.class,
jd.plugins.hoster.YouJizzCom.class,
jd.plugins.hoster.YouPornCom.class,
jd.plugins.hoster.YouPornDeutschCom.class,
jd.plugins.hoster.YouSavedIt.class,
jd.plugins.hoster.YouSendItCom.class,
// jd.plugins.hoster.YouWatchOrg.class,
jd.plugins.hoster.YoukuCom.class,
jd.plugins.hoster.YourFileLinkCom.class,
jd.plugins.hoster.YourFilesTo.class,
jd.plugins.hoster.YourFreePornUs.class,
jd.plugins.hoster.YourLustCom.class,
jd.plugins.hoster.YourUploadCom.class,
jd.plugins.hoster.Youtube.class,
// jd.plugins.hoster.YoutubeDashConfigPanel.class,
// jd.plugins.hoster.YoutubeDashV2.class,
jd.plugins.hoster.YunFileCom.class,
jd.plugins.hoster.YunPanCn.class,
jd.plugins.hoster.YunioCom.class,
jd.plugins.hoster.YuvutuCom.class,
jd.plugins.hoster.Yy12Cn.class,
jd.plugins.hoster.ZMagsCom.class,
jd.plugins.hoster.ZalaaCom.class,
jd.plugins.hoster.ZalilRu.class,
jd.plugins.hoster.ZalivalkaRu.class,
jd.plugins.hoster.ZaycevNet.class,
jd.plugins.hoster.ZbigzCom.class,
jd.plugins.hoster.ZdfDeMediathek.class,
jd.plugins.hoster.ZeroAPremium.class,
jd.plugins.hoster.Zevera.class,
jd.plugins.hoster.ZeveraCom.class,
jd.plugins.hoster.ZidduCom.class,
jd.plugins.hoster.ZinWaCom.class,
// jd.plugins.hoster.ZingLoadCom.class,
jd.plugins.hoster.ZippyTuneCom.class,
// jd.plugins.hoster.Zippysharecom.class,
jd.plugins.hoster.ZomgUploadCom.class
    );

    public static List<PluginInfo<PluginForHost>> list() {
        List<PluginInfo<PluginForHost>> ret = new ArrayList<PluginInfo<PluginForHost>>();
        for (Class<?> c : CLASSES) {
            ret.add(new PluginInfo<PluginForHost>(null, (Class<PluginForHost>)c));
        }
        return ret;
    }
}
